# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Micrel network device drivers.
#

obj-$(CONFIG_KS8842) += ks8842.o
obj-$(CONFIG_KS8851) += ks8851.o
obj-$(CONFIG_KS8851_MLL) += ks8851_mll.o
obj-$(CONFIG_KSZ884X_PCI) += ksz884x.o
obj-$(CONFIG_SPI_KSZ8795) += spi-ksz8795.o
obj-$(CONFIG_I2C_KSZ9897) += i2c-ksz9897.o
obj-$(CONFIG_SPI_KSZ9897) += spi-ksz9897.o
