dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += \
		imx8m-var-dart-sd-emmc-hdmi.dtb \
		imx8m-var-dart-sd-emmc-hdmi-4k.dtb \
		imx8m-var-dart-sd-emmc-dcss-lvds.dtb \
		imx8m-var-dart-sd-emmc-lcdif-lvds.dtb \
		imx8m-var-dart-emmc-wifi-hdmi.dtb \
		imx8m-var-dart-emmc-wifi-hdmi-4k.dtb \
		imx8m-var-dart-emmc-wifi-dcss-lvds.dtb \
		imx8m-var-dart-emmc-wifi-lcdif-lvds.dtb

always          := $(dtb-y)
subdir-y        := $(dts-dirs)
clean-files     := *.dtb

