dtb-$(CONFIG_ARCH_FSL_IMX8MQ) += \
		imx8m-var-dart-sd-emmc-hdmi.dtb \
		imx8m-var-dart-sd-emmc-lvds.dtb \
		imx8m-var-dart-sd-emmc-dual.dtb \
		imx8m-var-dart-emmc-wifi-hdmi.dtb \
		imx8m-var-dart-emmc-wifi-lvds.dtb \
		imx8m-var-dart-emmc-wifi-dual.dtb

always          := $(dtb-y)
subdir-y        := $(dts-dirs)
clean-files     := *.dtb

