#
#  Makefile for the Linux Controller Area Network SPI drivers.
#
obj-$(CONFIG_CAN_MCP25XXFD)	+= mcp25xxfd.o
mcp25xxfd-objs			:= mcp25xxfd_base.o
mcp25xxfd-objs			+= mcp25xxfd_can.o
mcp25xxfd-objs			+= mcp25xxfd_clock.o
mcp25xxfd-objs			+= mcp25xxfd_cmd.o
mcp25xxfd-objs			+= mcp25xxfd_crc.o
mcp25xxfd-objs			+= mcp25xxfd_debugfs.o
mcp25xxfd-objs			+= mcp25xxfd_ecc.o
mcp25xxfd-objs			+= mcp25xxfd_int.o
